sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

addons:
  apt:
    sources:
    - sourceline: 'ppa:hvr/ghcjs'
    update: true
    packages:
    - ghcjs-8.4

matrix:
  include:
  - ghc: 8.4.4

before_install:
  - export PATH=/opt/ghcjs/8.4/bin:$PATH
  - nvm install 8
  - node --version

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - cabal update
  - cabal build --enable-tests --enable-benchmarks

script:
  - echo 'No tests'

notifications:
  email: false
